import { StepConfig, SERVICES_LIST_EN, PLATFORMS_LIST_EN, CAMPAIGN_GOAL_TYPES_EN, TIMING_TYPES_EN } from '@/types/form'

export const formStepsEn: StepConfig[] = [
  {
    title: 'General Details',
    description: 'Basic Brief Information',
    fields: [
      {
        name: 'date',
        label: 'Date',
        type: 'date',
        required: true,
      },
      {
        name: 'submitterName',
        label: 'Brief Submitted By',
        type: 'text',
        placeholder: 'Full Name',
        required: true,
      },
      {
        name: 'clientName',
        label: 'Client Name',
        type: 'text',
        placeholder: 'Client Name',
        required: true,
      },
      {
        name: 'productService',
        label: 'Product / Service',
        type: 'text',
        placeholder: 'Short description',
        required: true,
      },
      {
        name: 'services',
        label: 'Which services are you interested in?',
        type: 'checkbox-group',
        required: true,
        options: SERVICES_LIST_EN,
      },
      {
        name: 'platforms',
        label: 'Relevant Platforms',
        type: 'checkbox-group',
        required: true,
        options: PLATFORMS_LIST_EN,
      },
      {
        name: 'campaignLaunchDate',
        label: 'Campaign Launch Date',
        type: 'date',
        required: true,
      },
    ],
  },
  {
    title: 'Background',
    description: 'Market & Competitor Information',
    fields: [
      {
        name: 'marketCategory',
        label: 'In which market and category do we operate?',
        type: 'textarea',
        placeholder: 'Describe the market and the category.',
        required: true,
      },
      {
        name: 'productDescription',
        label: 'Product / Service / Brand Description. What is the core value proposition? What is the USP?',
        type: 'textarea',
        placeholder: 'Describe the product and its unique advantage.',
        required: true,
      },
      {
        name: 'competitors',
        label: 'Who are the competitors and what activities/campaigns are they running?',
        type: 'textarea',
        placeholder: 'Detail the competitors and their initiatives.',
        required: true,
      },
      {
        name: 'challenge',
        label: 'What is the problem / challenge we need to address?',
        type: 'textarea',
        placeholder: 'Describe the main challenge.',
        required: true,
      },
    ],
  },
  {
    title: 'Target Audience',
    description: 'Understanding the Target Audience',
    fields: [
      {
        name: 'targetAudience',
        label: 'Who are we addressing?',
        type: 'textarea',
        placeholder: 'Describe the target audience.',
        required: true,
      },
      {
        name: 'audienceCharacteristics',
        label: 'Relevant characteristics of the target audience?',
        type: 'textarea',
        placeholder: 'Age, gender, interests, habits, etc.',
        required: true,
      },
      {
        name: 'audienceInsights',
        label: 'What is important for us to know about the audience?',
        type: 'textarea',
        placeholder: 'Key insights about the audience.',
        required: true,
      },
    ],
  },
  {
    title: 'Objectives',
    description: 'Campaign Goals & Expectations',
    fields: [
      {
        name: 'campaignGoalTypes',
        label: 'Campaign goal types (select options)',
        type: 'checkbox-group',
        required: true,
        options: CAMPAIGN_GOAL_TYPES_EN,
      },
      {
        name: 'campaignGoalsDescription',
        label: 'Describe the goals in detail',
        type: 'textarea',
        placeholder: 'Specify what we want to achieve.',
        required: true,
      },
      {
        name: 'desiredResponse',
        label: 'What would we like the audience to feel / do following the campaign?',
        type: 'textarea',
        placeholder: 'Desired audience response.',
        required: true,
      },
      {
        name: 'timingType',
        label: 'Specific campaign timing',
        type: 'select',
        required: true,
        options: TIMING_TYPES_EN,
      },
      {
        name: 'timingDetails',
        label: 'Timing details (season / new product launch / specific event)',
        type: 'textarea',
        placeholder: 'For example: summer season, new product launch, Passover event.',
        required: false,
      },
    ],
  },
  {
    title: 'Insight & Message',
    description: 'Core Insight and Key Message',
    fields: [
      {
        name: 'insight',
        label: 'What is the tension, dissonance, or aspiration in our target audience\'s life?',
        type: 'textarea',
        placeholder: 'Describe the central insight.',
        required: true,
      },
      {
        name: 'solution',
        label: 'How does our brand / product / service solve this problem?',
        type: 'textarea',
        placeholder: 'Describe how you solve the problem.',
        required: true,
      },
      {
        name: 'mainMessage',
        label: 'In one sentence — what is the most important thing to say?',
        type: 'textarea',
        placeholder: 'The main message in one sentence.',
        required: true,
      },
      {
        name: 'keyTakeaway',
        label: 'What do we want the consumer to remember from the campaign?',
        type: 'textarea',
        placeholder: 'What should remain in their memory.',
        required: true,
      },
    ],
  },
  {
    title: 'Requirements & Budget',
    description: 'Practical Requirements and Budget',
    fields: [
      {
        name: 'requirements',
        label: 'What is required? (Big idea, script, collaboration ideas, etc.)',
        type: 'textarea',
        placeholder: 'Specify what is required for the campaign.',
        required: true,
      },
      {
        name: 'campaignType',
        label: 'What type of campaign are we looking for? (Video, series, content asset, collaboration, etc.)',
        type: 'textarea',
        placeholder: 'Describe the type of campaign.',
        required: true,
      },
      {
        name: 'budget',
        label: 'Budget',
        type: 'text',
        placeholder: 'For example: $8,000',
        required: true,
      },
      {
        name: 'notes',
        label: 'Notes, ideas, and thoughts…',
        type: 'textarea',
        placeholder: 'Additional comments (optional)',
        required: false,
      },
    ],
  },
]
